# Archived Development Notebook

**Status:** Archived exploratory analysis

This notebook contains exploratory analyses, debugging investigations, preprocessing validation, or development experiments performed during construction of the Raman spectroscopy bacterial classification framework.

The analyses documented here supported repository development but are **not part of the finalized methodology** described in the README, documentation, or accompanying publication.

This notebook is preserved for transparency and reproducibility.

In [4]:
import sys
import os

# Add project root to Python path
sys.path.append(os.path.abspath(".."))

In [5]:
import numpy as np
import pandas as pd

from metadata.label_metadata import (
    LABEL_METADATA,
    get_strain_name,
    get_antibiotic_name,
    get_biological_category,
    get_full_metadata
)

In [7]:
DATA_DIR = "../data/raw"

X_REFERENCE_PATH = os.path.join(DATA_DIR, "X_reference.npy")
Y_REFERENCE_PATH = os.path.join(DATA_DIR, "y_reference.npy")

X_reference = np.load(X_REFERENCE_PATH)
y_reference = np.load(Y_REFERENCE_PATH)

print("X_reference shape:", X_reference.shape)
print("y_reference shape:", y_reference.shape)

X_reference shape: (60000, 1000)
y_reference shape: (60000,)

In [8]:
unique_labels = np.unique(y_reference)

print(unique_labels)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17.
 18. 19. 20. 21. 22. 23. 24. 25. 26. 27. 28. 29.]

In [9]:
rows = []

for label in unique_labels:

    rows.append({
        "Label ID": label,
        "Strain": get_strain_name(label),
        "Antibiotic": get_antibiotic_name(label),
        "Category": get_biological_category(label)
    })

label_df = pd.DataFrame(rows)

label_df

    Label ID             Strain     Antibiotic       Category
0        0.0        C. albicans    Caspofungin          Yeast
1        1.0        C. glabrata    Caspofungin          Yeast
2        2.0       K. aerogenes      Meropenem  Gram-negative
3        3.0          E. coli 1      Meropenem  Gram-negative
4        4.0          E. coli 2      Meropenem  Gram-negative
5        5.0         E. faecium     Daptomycin  Gram-positive
6        6.0      E. faecalis 1     Penicillin  Gram-positive
7        7.0      E. faecalis 2     Penicillin  Gram-positive
8        8.0         E. cloacae      Meropenem  Gram-negative
9        9.0    K. pneumoniae 1      Meropenem  Gram-negative
10      10.0    K. pneumoniae 2      Meropenem  Gram-negative
11      11.0       P. mirabilis      Meropenem  Gram-negative
12      12.0    P. aeruginosa 1            TZP  Gram-negative
13      13.0    P. aeruginosa 2            TZP  Gram-negative
14      14.0             MSSA 1     Vancomycin  Gram-positive
15      15.0             MSSA 3     Vancomycin  Gram-positive
16      16.0  MRSA 1 (isogenic)     Vancomycin  Gram-positive
17      17.0             MRSA 2     Vancomycin  Gram-positive
18      18.0             MSSA 2     Vancomycin  Gram-positive
19      19.0        S. enterica  Ciprofloxacin  Gram-negative
20      20.0     S. epidermidis     Vancomycin  Gram-positive
21      21.0     S. lugdunensis     Vancomycin  Gram-positive
22      22.0      S. marcescens      Meropenem  Gram-negative
23      23.0    S. pneumoniae 2    Ceftriaxone  Gram-positive
24      24.0    S. pneumoniae 1    Ceftriaxone  Gram-positive
25      25.0       S. sanguinis     Penicillin  Gram-positive
26      26.0     Group A Strep.     Penicillin  Gram-positive
27      27.0     Group B Strep.     Penicillin  Gram-positive
28      28.0     Group C Strep.     Penicillin  Gram-positive
29      29.0     Group G Strep.     Penicillin  Gram-positive

In [10]:
distribution_rows = []

for label in unique_labels:

    count = np.sum(y_reference == label)

    distribution_rows.append({
        "Label ID": label,
        "Strain": get_strain_name(label),
        "Samples": count,
        "Antibiotic": get_antibiotic_name(label),
        "Category": get_biological_category(label)
    })

distribution_df = pd.DataFrame(distribution_rows)

distribution_df.sort_values("Label ID")

    Label ID             Strain  Samples     Antibiotic       Category
0        0.0        C. albicans     2000    Caspofungin          Yeast
1        1.0        C. glabrata     2000    Caspofungin          Yeast
2        2.0       K. aerogenes     2000      Meropenem  Gram-negative
3        3.0          E. coli 1     2000      Meropenem  Gram-negative
4        4.0          E. coli 2     2000      Meropenem  Gram-negative
5        5.0         E. faecium     2000     Daptomycin  Gram-positive
6        6.0      E. faecalis 1     2000     Penicillin  Gram-positive
7        7.0      E. faecalis 2     2000     Penicillin  Gram-positive
8        8.0         E. cloacae     2000      Meropenem  Gram-negative
9        9.0    K. pneumoniae 1     2000      Meropenem  Gram-negative
10      10.0    K. pneumoniae 2     2000      Meropenem  Gram-negative
11      11.0       P. mirabilis     2000      Meropenem  Gram-negative
12      12.0    P. aeruginosa 1     2000            TZP  Gram-negative
13      13.0    P. aeruginosa 2     2000            TZP  Gram-negative
14      14.0             MSSA 1     2000     Vancomycin  Gram-positive
15      15.0             MSSA 3     2000     Vancomycin  Gram-positive
16      16.0  MRSA 1 (isogenic)     2000     Vancomycin  Gram-positive
17      17.0             MRSA 2     2000     Vancomycin  Gram-positive
18      18.0             MSSA 2     2000     Vancomycin  Gram-positive
19      19.0        S. enterica     2000  Ciprofloxacin  Gram-negative
20      20.0     S. epidermidis     2000     Vancomycin  Gram-positive
21      21.0     S. lugdunensis     2000     Vancomycin  Gram-positive
22      22.0      S. marcescens     2000      Meropenem  Gram-negative
23      23.0    S. pneumoniae 2     2000    Ceftriaxone  Gram-positive
24      24.0    S. pneumoniae 1     2000    Ceftriaxone  Gram-positive
25      25.0       S. sanguinis     2000     Penicillin  Gram-positive
26      26.0     Group A Strep.     2000     Penicillin  Gram-positive
27      27.0     Group B Strep.     2000     Penicillin  Gram-positive
28      28.0     Group C Strep.     2000     Penicillin  Gram-positive
29      29.0     Group G Strep.     2000     Penicillin  Gram-positive

In [11]:
Y_2018_PATH = os.path.join(DATA_DIR, "y_2018clinical.npy")
Y_2019_PATH = os.path.join(DATA_DIR, "y_2019clinical.npy")

y_2018 = np.load(Y_2018_PATH)
y_2019 = np.load(Y_2019_PATH)

print("2018 Clinical Labels:")
print(np.unique(y_2018))

print("\n2019 Clinical Labels:")
print(np.unique(y_2019))

2018 Clinical Labels:
[0. 2. 3. 5. 6.]

2019 Clinical Labels:
[0. 2. 3. 5. 6.]

In [12]:
print("2018 Clinical Mapping")
print("-" * 50)

for label in np.unique(y_2018):

    print(
        f"{int(label)} -> "
        f"{get_strain_name(int(label))}"
    )

print("\n2019 Clinical Mapping")
print("-" * 50)

for label in np.unique(y_2019):

    print(
        f"{int(label)} -> "
        f"{get_strain_name(int(label))}"
    )

2018 Clinical Mapping
--------------------------------------------------
0 -> C. albicans
2 -> K. aerogenes
3 -> E. coli 1
5 -> E. faecium
6 -> E. faecalis 1

2019 Clinical Mapping
--------------------------------------------------
0 -> C. albicans
2 -> K. aerogenes
3 -> E. coli 1
5 -> E. faecium
6 -> E. faecalis 1